# Simply NDNGateway configuration

# IP configuration
HTTP_HOST: localhost
HTTP_PORT: 1234

# IP transport configuration
TCP_POST: 4321
TCP_LISTEN: 5
TCP_MSGLEN: 1024
TCP_END_OF_PATH_CHAR: 0x00

# NDN configuration
NDN_URI_PREFIX: ccnx:/
NDN_URI_ROOT: ccnx:/gateway/
NDN_CACHE_TIME: 900 # 15 * 60 = 15 minutes