# Simply NDNGateway configuration

# IP configuration
HTTP_HOST: localhost
HTTP_PORT: 1234

# NDN configuration
NDN_URI_PREFIX: ccnx:/
NDN_URI_ROOT: ccnx:/gateway/
NDN_CACHE_TIME: 900 # 15 * 60 = 15 minutes